from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from crm.models import Company, Group, Department
from crm.views import *

urlpatterns = patterns("crm.views",
    url(r'^$',
		CompanyListView.as_view(),
		name="crm_company_list"
	),
	url(r'^group/list/$',
		GroupListView.as_view(),
		name="crm_group_list"
	),
	url(r'^group/detail/(?P<pk>\d+)/$',
		GroupDetailView.as_view(),
		name="crm_group_detail"
	),
	url(r'^group/edit/(?P<pk>\d+)/$',
		GroupUpdateView.as_view(),
		name="crm_group_edit"
	),
	url(r'^group/create/$',
		GroupCreateView.as_view(),
		name="crm_group_create"
	),
    url(r'^company/detail/(?P<pk>\d+)/$',
		CompanyDetailView.as_view(),
		name="crm_company_detail"
	),
    url(r'^company/edit/(?P<pk>\d+)/$',
		CompanyUpdateView.as_view(),
		name="crm_company_edit"
	),
	url(r'^company/create/$',
		CompanyCreateView.as_view(),
		name="crm_company_create"
	),
	url(r'^company/search/$',
		CompanySearchView.as_view(),
		name="crm_company_search"
	),
    url(r'^department/detail/(?P<pk>\d+)/$',
		DepartmentDetailView.as_view(),
		name="crm_department_detail"
	),
    url(r'^department/edit/(?P<pk>\d+)/$',
		DepartmentUpdateView.as_view(),
		name="crm_department_edit"
	),
    url(r'^company/add_department/(?P<pk>\d+)/$',
		DepartmentCreateView.as_view(),
		name="crm_department_create"
	),
	##
	## QUOTATION URLS
	##
	url(r'^quotation/create/(?P<pk>\d+)/$',
		QuotationCreateView.as_view(),
		name="crm_quotation_create"
	),
	url(r'^quotation/list/$',
		QuotationListView.as_view(),
		name="crm_quotation_list"
	),
	url(r'^quotation/list/(?P<pk>\d+)$',
		CompanyQuotationListView.as_view(),
		name="crm_companyquotation_list"
	),
	url(r'^quotation/detail/(?P<pk>\d+)/$',
		QuotationDetailView.as_view(),
		name="crm_quotation_detail"
	),
	url(r'^quotation/pdf/(?P<pk>\d+)/$',
		QuotationPdfView.as_view(),
		name="crm_quotation_pdf"
	),
	url(r'^quotation/edit/(?P<pk>\d+)/$',
		QuotationUpdateView.as_view(),
		name="crm_quotation_update"
	),
	url(r'^quotationitem/create/$',
		QuotationItemCreateView.as_view(),
		name="crm_quotationitem_create"
	),
	url(r'^quotationitem/edit/(?P<pk>\d+)/$',
		QuotationItemUpdateView.as_view(),
		name="crm_quotationitem_update"
	),
	url(r'^quotationitem/delete/(?P<pk>\d+)/$',
		QuotationItemDeleteView.as_view(),
		name="crm_quotationitem_delete"
	),
	##
	## CONTRACT URLS
	##
	url(r'^contract/create/(?P<pk>\d+)/$',
		ContractCreateView.as_view(),
		name="crm_contract_create"
	),
	url(r'^contract/list/$',
		ContractListView.as_view(),
		name="crm_contract_list"
	),
	url(r'^contract/list/(?P<pk>\d+)$',
		CompanyContractListView.as_view(),
		name="crm_companycontract_list"
	),
	url(r'^contract/detail/(?P<pk>\d+)/$',
		ContractDetailView.as_view(),
		name="crm_contract_detail"
	),
	url(r'^contract/pdf/(?P<pk>\d+)/$',
		ContractPdfView.as_view(),
		name="crm_contract_pdf"
	),
	url(r'^contract/edit/(?P<pk>\d+)/$',
		ContractUpdateView.as_view(),
		name="crm_contract_update"
	),
	url(r'^contractitem/create/$',
		ContractItemCreateView.as_view(),
		name="crm_contractitem_create"
	),
	url(r'^contractitem/edit/(?P<pk>\d+)/$',
		ContractItemUpdateView.as_view(),
		name="crm_contractitem_update"
	),
	url(r'^contractitem/delete/(?P<pk>\d+)/$',
		ContractItemDeleteView.as_view(),
		name="crm_contractitem_delete"
	),
	url(r'^quotation/tocontract/(?P<pk>\d+)/$',
		QuotationToContractView.as_view(),
		name="crm_quotation_to_contract"
	),
)
